### ISSUE TITLE
[HW] <Ketrina Sterna>

### ISSUE THREAD

**Issue by kketrinaa** [datastaxdevs/workshop-social-media-tiktok#57]
**Name:** <Ketrina Sterna>
**Email:** <ketriina.sterna@gmail.com>
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![Homework, Ketrina Sterna](https://user-images.githubusercontent.com/84866469/120196748-e1573000-c228-11eb-902a-48cef4e69065.png)
![Homework](https://user-images.githubusercontent.com/84866469/120196756-e3b98a00-c228-11eb-90e3-eacdb4652f77.png)

**Comment by SonicDMG** [comment]
Hey there Ketriina, go ahead and disregard the response I sent to your github account. I happened to see that submission first, but turns out you submitted to our repo as well. Nice job completing the homework and thank you. Here you go -> https://api.badgr.io/public/assertions/BWXVqy-YQFSGMiwurFaH6g?identity__email=ketriina.sterna%40gmail.com
